### ISSUE TITLE
Github Action failing with message "Failed to parse URL from undefined"

### ISSUE THREAD

**Issue by DaniAkash** [snaplet/vercel-action#6]
This is my workflow file:
```yml
name: Vercel Preview Deployment

env:
  VERCEL_ACCESS_TOKEN: ${{ secrets.VERCEL_ACCESS_TOKEN }}
  VERCEL_PROJECT_ID: <project-id>

on:
  pull_request:
    types: [opened, synchronize, closed]

jobs:
  deploy-vercel-preview:
    if: ${{ github.event.action == 'opened' || github.event.action == 'synchronize' }}
    runs-on: ubuntu-latest
    steps:
      - uses: snaplet/vercel-action@v2
  delete-vercel-preview:
    if: ${{ github.event.action == 'closed' }}
    runs-on: ubuntu-latest
    steps:
      - uses: snaplet/vercel-action@v2
        with:
          delete: true
```

Based on the above workflow file, I'm getting the following error message when a new pull request is created:

```
Creating deploy hook...
Deploy hook created.
Creating deployment...
node:internal/deps/undici/undici:5573
            throw new TypeError("Failed to parse URL from " + input, { cause: err });
                  ^

TypeError: Failed to parse URL from undefined
    at new Request (node:internal/deps/undici/undici:5573:19)
    at Agent.fetch2 (node:internal/deps/undici/undici:6[37](https://github.com/realtimeskills/oslash/actions/runs/3636809230/jobs/6137131079#step:2:40)1:25)
    ... 2 lines matching cause stack trace ...
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  [cause]: TypeError [ERR_INVALID_URL]: Invalid URL
      at new NodeError (node:internal/errors:387:5)
      at URL.onParseError (node:internal/url:565:9)
      at new URL (node:internal/url:641:5)
      at new Request (node:internal/deps/undici/undici:5571:25)
      at Agent.fetch2 (node:internal/deps/undici/undici:6371:25)
      at fetch (node:internal/deps/undici/undici:7200:20)
      at file:///home/runner/work/_actions/snaplet/vercel-action/v2/scripts/deploy.mjs:49:23
      at processTicksAndRejections (node:internal/process/task_queues:96:5) {
    input: 'undefined',
    code: 'ERR_INVALID_URL'
  }
}
Error: Process completed with exit code 1.
```
